from pathlib import Path

import numpy as np
import pandas as pd


def make_synthetic_prices(
    n_assets: int = 20,
    n_years: int = 15,
    seed: int = 42,
    annual_mu: float = 0.08,
    annual_sigma: float = 0.25,
) -> pd.DataFrame:
    """
    Monthly close-price panel generated by geometric random walks.

    Each asset i gets:
      drift_i  ~ N(annual_mu, 0.05)        heterogeneous expected returns
      sigma_i  ~ Uniform(0.15, 0.40)       heterogeneous volatility
      monthly log-return ~ N(drift_i/12 - sigma_i^2/24,  sigma_i/sqrt(12))

    The Ito correction (-sigma^2/24 in the monthly step) ensures
    E[P_T] grows at roughly e^(drift * T).

    Missing-data rule: none — synthetic panel is complete by construction.
    """
    rng = np.random.default_rng(seed)
    n_periods = n_years * 12 + 1  # +1 so we have n_years*12 monthly returns

    drifts = rng.normal(annual_mu, 0.05, n_assets)
    sigmas = rng.uniform(0.15, 0.40, n_assets)

    monthly_mean = drifts / 12 - sigmas**2 / 24
    monthly_std = sigmas / np.sqrt(12)

    log_rets = rng.normal(
        monthly_mean[:, None],
        monthly_std[:, None],
        size=(n_assets, n_periods - 1),
    )

    prices = np.ones((n_assets, n_periods))
    prices[:, 1:] = np.cumprod(np.exp(log_rets), axis=1)

    dates = pd.date_range(start="2005-01-31", periods=n_periods, freq="ME")
    columns = [f"ASSET_{i:02d}" for i in range(n_assets)]
    return pd.DataFrame(prices.T, index=dates, columns=columns)


def load_csv_prices(path: str | Path) -> pd.DataFrame:
    """
    Load a price panel from CSV.

    Expected format:
      - First column: date (any pandas-parseable format), used as index.
      - Remaining columns: one per asset, containing close prices.

    Missing-data handling:
      1. Assets with > 20 % missing rows are dropped entirely.
      2. Remaining gaps are forward-filled (last known price) then
         back-filled for any leading NaN.  This is documented here so
         callers know that spurious zero-return periods may be introduced
         at the edges of an asset's listing.
    """
    df = pd.read_csv(path, index_col=0, parse_dates=True)
    df = df.sort_index()

    missing_frac = df.isna().mean()
    df = df.loc[:, missing_frac <= 0.20]

    df = df.ffill().bfill()
    return df
